// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3d93162d-a28a-423d-8842-5ecbf0c38da6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6vxcPJZpg",
    "aws_user_pools_web_client_id": "7fsu868naij64j7rvppmk6lfr9",
    "oauth": {}
};


export default awsmobile;
